### ISSUE TITLE
Domain Name can’t deploy!

### ISSUE THREAD

**Issue by rezavn** [schors/tgdante2#19]
Hi dear developer.
I launched Shadowsocks-R Server recently for Holding #Digital_Resistance.
The reason that i launched SSR server was Socks5 is Banned in Iran.

Now i want to publish my server for free but idont want others to use ip.
I want them to use domain name.
I can not link my domain which is ShadowSocks-r.ga to my ubuntu Server.
Please help me with that.
I can give you access to my server.

**Comment by landergate** [comment]
@rezavn Usually it's enough to purchase any domain name and create DNS record with type "A", directing it to your server's IP.

**Comment by rezavn** [comment]
I created one DNS but ican not connect to it.

**Comment by landergate** [comment]
@rezavn Can you share it here?

**Comment by landergate** [comment]
@rezavn 
Basically you need to make sure that your DNS record is resolvable for outside world. Try doing `dig -t A yourdomain.name` from some other server or user to check if it's resolvable at all.

**Comment by rezavn** [comment]
dig -t A shadowsocks-r.ga

; <<>> DiG 9.10.3-P4-Ubuntu <<>> -t A shadowsocks-r.ga
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 61692
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 2, ADDITIONAL: 3

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;shadowsocks-r.ga.              IN      A

;; ANSWER SECTION:
shadowsocks-r.ga.       14400   IN      A       185.162.235.17

;; AUTHORITY SECTION:
shadowsocks-r.ga.       14400   IN      NS      ns2.shadowsocks-r.ga.
shadowsocks-r.ga.       14400   IN      NS      ns1.shadowsocks-r.ga.

;; ADDITIONAL SECTION:
ns1.shadowsocks-r.ga.   14400   IN      A       185.162.235.17
ns2.shadowsocks-r.ga.   14400   IN      A       185.162.235.17

;; Query time: 0 msec
;; SERVER: 185.162.235.17#53(185.162.235.17)
;; WHEN: Tue May 22 06:03:50 EDT 2018
;; MSG SIZE  rcvd: 129

i received this

**Comment by landergate** [comment]
@rezavn 
Well, for me this domain is not available.
It would be a better idea to delegate DNS records management not on your own self-hosted DNS-server, but on registrar's, if other users has connectivity issues with your own NS.

**Comment by rezavn** [comment]
In english please:\ im beginner sorry:(

**Comment by rezavn** [comment]
185.162.235.17

**Comment by landergate** [comment]
@rezavn 
Where do you manage your DNS records? Is it self-hosted DNS-server, or your domain registrar's?

**Comment by rezavn** [comment]
http://s8.picofile.com/file/8327128084/Untitled.png

**Comment by rezavn** [comment]
i set the DNS into this

**Comment by landergate** [comment]
@rezavn 
It was a bad idea to publish ssh access here. Please remove it while it's not too late.

**Comment by rezavn** [comment]
Ok bro i removed it:(

**Comment by KostyaEsmukov** [comment]
Please stop. This is inappropriate place for such discussion. This is not a chat. What you write is public, and each your comment is emailed to ~30 watching users. Use private email instead.

**Comment by landergate** [comment]
@rezavn
Considering your screenshot and current NS connectivity/configuartion issues, you can just switch your domain to "Use default nameservers" and then manage records with "Manage DNS" in your registrar's panel.

Again, all of this is totally out of scope of "tgdante2" project, so it would be a better idea to forward your questions to your DNS provider or any Linux support chat available.

**Comment by rezavn** [comment]
Thanks By the way for helping.
