### ISSUE TITLE
Main functional doesn't work

### ISSUE THREAD

**Issue by werelaxe** [schors/tgdante2#3]
After running
`docker run -d --net=host --restart unless-stopped -e PORT=1080 -e USER=user0 -e PASS=secret0 --name tgdante schors/tgdante2`
container starts succesfully.
But
`curl -x socks5://user0:secret0@localhost:1080 https://web.telegram.org`
returns
`curl: (35) gnutls_handshake() failed: Access was denied`

**Comment by schors** [comment]
Oops.. Do you set up your proxy outside Russian jurisdiction?

**Comment by werelaxe** [comment]
Oh, yes... Probably, my provider is already blocked me. Sorry for  this.
