### ISSUE TITLE
tzdata

### ISSUE THREAD

**Issue by aekv** [schors/tgdante2#4]
Привет,

Для установки корректного времени в контейнере, можно ли добавить tzdata в image?

Еще в логах сыпятся постоянно сообщения: _blocked by higher-level socks-rule #14_

**Comment by schors** [comment]
Время в контейнерах исключительно хостовое. Бессмысленно туда tzdata класть.
Логи отдельным issue. Свой внешний IP можно "запикать" крестиками.
